import { createClient } from "@sanity/client";
import { createImageUrlBuilder } from "@sanity/image-url";

// Default configuration for Sanity
// If project ID is not set in env, we will fall back to local storage / mock data
export const sanityConfig = {
  projectId: import.meta.env.VITE_SANITY_PROJECT_ID || "demo-project-id",
  dataset: import.meta.env.VITE_SANITY_DATASET || "production",
  useCdn: true,
  apiVersion: "2024-05-04",
};

export const sanityClient = createClient(sanityConfig);

const builder = createImageUrlBuilder(sanityClient);

export function urlFor(source: any) {
  return builder.image(source);
}

// Fallback initial content if Sanity is not connected or local storage is empty
export const defaultContent = {
  welcome: {
    tagline: "Adityagenset",
    titleLine1: "Silent Power.",
    titleLine2: "Engineered to last.",
    titleLine3: "Since 1997.",
    buttonText: "Enter site →"
  },
  productConfig: {
    pageLabel: "PRODUCT RANGE",
    sectionTitle: "Our Products",
    sectionSubtitle: "Industrial-grade reliability",
    category1Title: "DG SETS",
    category1Desc: "High-performance Diesel generator sets for industrial and commercial power.",
    category2Title: "NON STANDARD",
    category2Desc: "Customized containers and specialized enclosures tailored to unique requirements.",
    ctaText: "Select Category",
  },
  showcase: {
    heroTitle: "Aditya Genset",
    heroSubtitle: "Aditya Tech Mech Pvt. Ltd.",
    heroTagline: "Empowering India with Uninterrupted Power Since 1997",
    heroCertification: "ISO 9001:2015 Certified",
    heroContactPhoneLabel: "Call Us",
    heroContactPhone: "+91 99249 68777",
    heroContactEmailLabel: "Email",
    heroContactEmail: "sales@adityagenset.com",
    heroContactWebsiteLabel: "Website",
    heroContactWebsite: "www.adityagenset.com",
    seoTitle: "Get Your Silent Diesel Generators Today | Aditya — ISO Certified",
    seoDescription: "ISO 9001:2015 certified manufacturer of silent diesel generator sets, 15–500 kVA. Pan-India delivery. Trusted since 1997.",
    featuredBadge: "Featured · 62.5 kVA",
    featuredButton: "Explore Specs",
    featuredStat1Value: "62.5",
    featuredStat1Label: "kVA",
    featuredStat2Value: "75",
    featuredStat2Label: "dB(A)",
    featuredStat3Value: "CPCB IV+",
    featuredStat3Label: "Compliant",
  },
  companyOverview: {
    sectionLabel: "About Us",
    heading: "Company Overview",
    description: "Aditya Tech Mech is a leading manufacturer and supplier of silent diesel generator sets. We engineer dependable power solutions tailored for India's demanding industrial and commercial environments.",
    stat1Label: "Headquarters",
    stat1Value: "Silvassa",
    stat2Label: "Offices",
    stat2Value: "Surat, Gujarat",
    stat3Label: "Founder",
    stat3Value: "Murlidhar Nair",
    kpi1Value: "1997",
    kpi1Label: "Founded",
    kpi2Value: "25+",
    kpi2Label: "Years Experience",
    kpi3Value: "14+",
    kpi3Label: "Cities Served",
    kpi4Value: "100%",
    kpi4Label: "Customer Satisfaction",
    clientsTitle: "Proudly Serving",
    client1: "Private enterprises",
    client2: "Government bodies",
    client3: "Indian Railways",
    client4: "Indian Army",
  },
  missionVision: {
    missionTitle: "Our Mission",
    missionItem1: "Deliver high-quality products and services",
    missionItem2: "Be cost-competitive",
    missionItem3: "Serve all power needs: Baseload, Standby, Critical standby",
    visionTitle: "Our Vision",
    visionItem1: "Become a benchmark in the power industry",
    visionItem2: "Provide world-class products",
    visionItem3: "Driven by: Integrity, Teamwork, Continuous improvement",
  },
  trustGainers: {
    sectionLabel: "Our Strengths",
    heading: "Why Choose Us",
    item1Title: "ISO 9001:2015",
    item1Body: "Certified for highest quality standards.",
    item2Title: "25+ Years Experience",
    item2Body: "Industry expertise since 1997.",
    item3Title: "Nationwide Delivery",
    item3Body: "Strong logistics network across India.",
    item4Title: "Trusted OEM Partnerships",
    item4Body: "Tied up with Escorts-Kubota & Baudouin.",
    item5Title: "Silent & Eco-Friendly",
    item5Body: "CPCB IV+ compliant sustainable technology.",
    item6Title: "Trusted By Leaders",
    item6Body: "Indian Railways, Army, Amazon & more.",
  },
  manufacturingProcess: {
    sectionLabel: "Workflow",
    heading: "Manufacturing Process",
    description: "Our 4-step workflow ensures every generator set meets stringent quality standards before it reaches your site.",
    step1Title: "Procuring",
    step1Desc: "High-quality raw materials sourced from trusted vendors.",
    step2Title: "Assembling",
    step2Desc: "Skilled engineering assembly with precision and care.",
    step3Title: "Testing",
    step3Desc: "Rigorous load & performance testing to ensure reliability.",
    step4Title: "Delivering",
    step4Desc: "Pan-India logistics + professional installation.",
  },
  contactCTA: {
    heading1: "Let's Power Your",
    headingAccent: "Future",
    description: "Together we keep India running — contact us for a free consultation",
    phoneLabel: "Phone",
    phoneValue: "+91 99249 68777",
    emailLabel: "Email",
    emailValue: "sales@adityagenset.com",
    websiteLabel: "Website",
    websiteValue: "www.adityagenset.com",
    addressesTitle: "Addresses",
    address1Title: "Manufacturing Unit",
    address1Body: "Plot No.29A/B, Survey No.208, Govt Ind. Estate, Phase 2, Pipariya, Silvassa – 396230",
    address2Title: "Corporate Office",
    address2Body: "Shop No.53, 2nd Floor, Aakash Business Centre, Piplod, Surat – 395007, Gujarat",
    tagline: "\"We Stand When Power Sleeps!\"",
  },
  statStrip: {
    stat1Value: "27+",
    stat1Label: "Years of trust",
    stat2Value: "500 kVA",
    stat2Label: "Up to",
    stat3Value: "36+",
    stat3Label: "Models in catalog",
  },
  oemPartners: {
    sectionLabel: "Engine Partners",
    heading: "Our OEM Partners",
    partner1Name: "Escorts-Kubota",
    partner1Tag: "Authorized OEM",
    partner2Name: "Baudouin",
    partner2Tag: "Engine Partner",
    partner3Name: "Kohler",
    partner3Tag: "Engine Partner",
  },
  dealerNetwork: {
    sectionLabel: "Pan-India Presence",
    heading: "Service Locations",
    description: "From metros to remote industrial corridors — our authorized dealers and service partners keep you powered, everywhere in India.",
    // Cities as a newline-separated list — users can add or remove lines in the editor
    cities: "Silvassa (HQ)\nSurat\nVadodara\nVapi\nRajkot\nBhavnagar\nJamnagar\nGandhidham\nMehsana\nJaipur\nJodhpur\nUdaipur\nKota\nAlwar\nAjmer",
  },
  happyCustomers: {
    sectionLabel: "Clients",
    heading: "Trusted Clients",
  },
  siteFooter: {
    aboutText: "ISO 9001:2015 certified manufacturer of silent diesel generator sets, 15–500 kVA. Empowering India with uninterrupted power since 1997.",
    exploreTitle: "Explore",
    contactTitle: "Contact",
    phone: "+91 99249 68777",
    email: "sales@adityagenset.com",
    address: "Silvassa, India",
    copyrightText: "Aditya Tech Mech. All rights reserved.",
    certificationText: "An ISO 9001:2015 Certified Company",
  },
  dgSetsCategory: {
    seoTitle: "DG Sets — Aditya Genset",
    seoDescription: "Browse 30+ DG sets, run side-by-side comparisons, and generate quotes in one session.",
    pageTitle: "Find the right power solution.",
    pageSubtitle: "Browse 30+ DG sets, run side-by-side comparisons, and generate quotes in one session.",
    resultsHeader: "Available DG Sets",
    noResultsTitle: "No generators found",
    noResultsSubtitle: "Try adjusting your filters or search query",
    badgeBestSeller: "Best Seller",
    badgePopular: "Popular",
    cardKvaLabel: "kVA",
    cardEngineLabel: "Engine",
    cardFuelLabel: "Fuel",
    cardNoiseLabel: "Noise",
    cardCtaText: "View Details",
  },
  productsData: {
    product_1_model: "ATMBD 250",
    product_1_kva: "250",
    product_1_engine: "Baudouin",
    product_1_application: "Prime",
    product_1_fuel: "52.5 L/h",
    product_1_noise: "73 dB(A)",
    product_1_compliance: "CPCB IV+",
    product_2_model: "ATMBD 320",
    product_2_kva: "320",
    product_2_engine: "Baudouin",
    product_2_application: "Prime",
    product_2_fuel: "67.2 L/h",
    product_2_noise: "74 dB(A)",
    product_2_compliance: "CPCB IV+",
    product_3_model: "ATMBD 400",
    product_3_kva: "400",
    product_3_engine: "Baudouin",
    product_3_application: "Prime",
    product_3_fuel: "84 L/h",
    product_3_noise: "74 dB(A)",
    product_3_compliance: "CPCB IV+",
    product_4_model: "ATMBD 450",
    product_4_kva: "450",
    product_4_engine: "Baudouin",
    product_4_application: "Prime",
    product_4_fuel: "94.5 L/h",
    product_4_noise: "74 dB(A)",
    product_4_compliance: "CPCB IV+",
    product_5_model: "ATMBD 500",
    product_5_kva: "500",
    product_5_engine: "Baudouin",
    product_5_application: "Standby",
    product_5_fuel: "105 L/h",
    product_5_noise: "75 dB(A)",
    product_5_compliance: "CPCB IV+",
    product_6_model: "ATMBD 625",
    product_6_kva: "625",
    product_6_engine: "Baudouin",
    product_6_application: "Standby",
    product_6_fuel: "131.3 L/h",
    product_6_noise: "75 dB(A)",
    product_6_compliance: "CPCB IV+",
    product_7_model: "ATMBD 750",
    product_7_kva: "750",
    product_7_engine: "Baudouin",
    product_7_application: "Standby",
    product_7_fuel: "157.5 L/h",
    product_7_noise: "76 dB(A)",
    product_7_compliance: "CPCB IV+",
    product_8_model: "ATMBD 910",
    product_8_kva: "910",
    product_8_engine: "Baudouin",
    product_8_application: "Standby",
    product_8_fuel: "191.1 L/h",
    product_8_noise: "77 dB(A)",
    product_8_compliance: "CPCB IV+",
    product_9_model: "ATMBD 1010",
    product_9_kva: "1010",
    product_9_engine: "Baudouin",
    product_9_application: "Continuous",
    product_9_fuel: "212.1 L/h",
    product_9_noise: "77 dB(A)",
    product_9_compliance: "CPCB IV+",
    product_10_model: "ATMBD 1250",
    product_10_kva: "1250",
    product_10_engine: "Baudouin",
    product_10_application: "Continuous",
    product_10_fuel: "262.5 L/h",
    product_10_noise: "78 dB(A)",
    product_10_compliance: "CPCB IV+",
    product_11_model: "ATMBD 1500",
    product_11_kva: "1500",
    product_11_engine: "Baudouin",
    product_11_application: "Continuous",
    product_11_fuel: "315 L/h",
    product_11_noise: "80 dB(A)",
    product_11_compliance: "CPCB IV+",
    product_12_model: "ATMBD 1850",
    product_12_kva: "1850",
    product_12_engine: "Baudouin",
    product_12_application: "Continuous",
    product_12_fuel: "388.5 L/h",
    product_12_noise: "81 dB(A)",
    product_12_compliance: "CPCB IV+",
    product_13_model: "ATMBD 2000",
    product_13_kva: "2000",
    product_13_engine: "Baudouin",
    product_13_application: "Continuous",
    product_13_fuel: "420 L/h",
    product_13_noise: "82 dB(A)",
    product_13_compliance: "CPCB IV+",
    product_14_model: "ATMBD 2250",
    product_14_kva: "2250",
    product_14_engine: "Baudouin",
    product_14_application: "Continuous",
    product_14_fuel: "472.5 L/h",
    product_14_noise: "83 dB(A)",
    product_14_compliance: "CPCB IV+",
    product_15_model: "ATMBD 2500",
    product_15_kva: "2500",
    product_15_engine: "Baudouin",
    product_15_application: "Continuous",
    product_15_fuel: "525 L/h",
    product_15_noise: "85 dB(A)",
    product_15_compliance: "CPCB IV+",
    product_16_model: "ATM EKL 7.5-IV",
    product_16_kva: "7.5",
    product_16_engine: "Escorts",
    product_16_application: "Prime",
    product_16_fuel: "2 L/h",
    product_16_noise: "69 dB(A)",
    product_16_compliance: "CPCB IV",
    product_17_model: "ATM EKL 10-IV",
    product_17_kva: "10",
    product_17_engine: "Escorts",
    product_17_application: "Prime",
    product_17_fuel: "2.7 L/h",
    product_17_noise: "69 dB(A)",
    product_17_compliance: "CPCB IV",
    product_18_model: "ATM EKL 15 (2 Cyl)-IV",
    product_18_kva: "15",
    product_18_engine: "Escorts",
    product_18_application: "Prime",
    product_18_fuel: "4.1 L/h",
    product_18_noise: "70 dB(A)",
    product_18_compliance: "CPCB IV",
    product_19_model: "ATM EKL 15 (3 Cyl)-IV",
    product_19_kva: "15",
    product_19_engine: "Escorts",
    product_19_application: "Prime",
    product_19_fuel: "4.1 L/h",
    product_19_noise: "70 dB(A)",
    product_19_compliance: "CPCB IV",
    product_20_model: "ATM EKL 20 (2 Cyl)-IV",
    product_20_kva: "20",
    product_20_engine: "Escorts",
    product_20_application: "Prime",
    product_20_fuel: "5.4 L/h",
    product_20_noise: "70 dB(A)",
    product_20_compliance: "CPCB IV",
    product_21_model: "ATM EKL 20 (3 Cyl)-IV",
    product_21_kva: "20",
    product_21_engine: "Escorts",
    product_21_application: "Prime",
    product_21_fuel: "5.4 L/h",
    product_21_noise: "70 dB(A)",
    product_21_compliance: "CPCB IV",
    product_22_model: "ATM EKL 25-IV",
    product_22_kva: "25",
    product_22_engine: "Escorts",
    product_22_application: "Prime",
    product_22_fuel: "6.8 L/h",
    product_22_noise: "71 dB(A)",
    product_22_compliance: "CPCB IV",
    product_23_model: "ATM EKL 30-IV",
    product_23_kva: "30",
    product_23_engine: "Escorts",
    product_23_application: "Prime",
    product_23_fuel: "8.1 L/h",
    product_23_noise: "71 dB(A)",
    product_23_compliance: "CPCB IV",
    product_24_model: "ATM EKL 35 Prime",
    product_24_kva: "35",
    product_24_engine: "Escorts",
    product_24_application: "Prime",
    product_24_fuel: "9.5 L/h",
    product_24_noise: "72 dB(A)",
    product_24_compliance: "CPCB IV",
    product_25_model: "ATM EKL 35 Standby",
    product_25_kva: "35",
    product_25_engine: "Escorts",
    product_25_application: "Standby",
    product_25_fuel: "9.5 L/h",
    product_25_noise: "72 dB(A)",
    product_25_compliance: "CPCB IV",
    product_26_model: "ATM EKL 40-IV",
    product_26_kva: "40",
    product_26_engine: "Escorts",
    product_26_application: "Prime",
    product_26_fuel: "10.8 L/h",
    product_26_noise: "72 dB(A)",
    product_26_compliance: "CPCB IV",
    product_27_model: "ATM EKL 45 Standby",
    product_27_kva: "45",
    product_27_engine: "Escorts",
    product_27_application: "Standby",
    product_27_fuel: "12.2 L/h",
    product_27_noise: "73 dB(A)",
    product_27_compliance: "CPCB IV",
    product_28_model: "ATM EKL 45 Prime",
    product_28_kva: "45",
    product_28_engine: "Escorts",
    product_28_application: "Prime",
    product_28_fuel: "12.2 L/h",
    product_28_noise: "73 dB(A)",
    product_28_compliance: "CPCB IV",
    product_29_model: "ATM EKL 50-IV",
    product_29_kva: "50",
    product_29_engine: "Escorts",
    product_29_application: "Prime",
    product_29_fuel: "13.5 L/h",
    product_29_noise: "73 dB(A)",
    product_29_compliance: "CPCB IV",
    product_30_model: "ATM EKL 58.5-IV",
    product_30_kva: "58.5",
    product_30_engine: "Escorts",
    product_30_application: "Prime",
    product_30_fuel: "15.8 L/h",
    product_30_noise: "74 dB(A)",
    product_30_compliance: "CPCB IV",
  },
  showcaseData: {
    productName: "62.5 kVA Silent DG Set",
    pageLabel: "Showcase",
    pageSubtitle: "A 6-chapter walkthrough — scroll to explore each system.",
    presentModeBtn: "Present Mode",
    chapter_0_title: "62.5 kVA Silent DG Set",
    chapter_0_tagline: "Industrial-grade reliability, whisper-quiet by design.",
    chapter_0_h0_label: "Prime power",
    chapter_0_h0_value: "62.5",
    chapter_0_h0_suffix: " kVA",
    chapter_0_h1_label: "Sound @ 1m",
    chapter_0_h1_value: "75",
    chapter_0_h1_suffix: " dB(A)",
    chapter_0_h2_label: "Heritage",
    chapter_0_h2_value: "27",
    chapter_0_h2_suffix: "+ yrs",
    chapter_0_spec0_label: "Model",
    chapter_0_spec0_value: "ADG-62.5S",
    chapter_0_spec1_label: "Rating",
    chapter_0_spec1_value: "62.5 kVA / 50 kW",
    chapter_0_spec2_label: "Compliance",
    chapter_0_spec2_value: "CPCB IV+",
    chapter_1_title: "Engine",
    chapter_1_tagline: "Built for continuous duty and tight load response.",
    chapter_1_spec0_label: "Configuration",
    chapter_1_spec0_value: "4-cylinder, inline",
    chapter_1_spec1_label: "Aspiration",
    chapter_1_spec1_value: "Turbocharged",
    chapter_1_spec2_label: "Displacement",
    chapter_1_spec2_value: "~3.9 L",
    chapter_1_spec3_label: "Cooling",
    chapter_1_spec3_value: "Water-cooled",
    chapter_1_spec4_label: "Fuel",
    chapter_1_spec4_value: "High-speed diesel",
    chapter_2_title: "Power Output",
    chapter_2_tagline: "Clean, stable 3-phase power for sensitive loads.",
    chapter_2_spec0_label: "Rating",
    chapter_2_spec0_value: "62.5 kVA / 50 kW",
    chapter_2_spec1_label: "Voltage",
    chapter_2_spec1_value: "415 V",
    chapter_2_spec2_label: "Frequency",
    chapter_2_spec2_value: "50 Hz",
    chapter_2_spec3_label: "Phase",
    chapter_2_spec3_value: "3-phase, 4-wire",
    chapter_2_spec4_label: "Power factor",
    chapter_2_spec4_value: "0.8 lagging",
    chapter_3_title: "Sound & Enclosure",
    chapter_3_tagline: "CPCB IV+ compliant. Engineered to disappear into its environment.",
    chapter_3_spec0_label: "Sound level",
    chapter_3_spec0_value: "75 dB(A) @ 1m",
    chapter_3_spec1_label: "At 7m",
    chapter_3_spec1_value: "63 dB(A)",
    chapter_3_spec2_label: "Construction",
    chapter_3_spec2_value: "1.6 mm CRCA panels",
    chapter_3_spec3_label: "Insulation",
    chapter_3_spec3_value: "PU foam, 50 mm",
    chapter_3_spec4_label: "Finish",
    chapter_3_spec4_value: "7-tank powder coat",
    chapter_4_title: "Dimensions & Weight",
    chapter_4_tagline: "Compact footprint, easy to site and service.",
    chapter_4_spec0_label: "Length",
    chapter_4_spec0_value: "2400 mm",
    chapter_4_spec1_label: "Width",
    chapter_4_spec1_value: "1050 mm",
    chapter_4_spec2_label: "Height",
    chapter_4_spec2_value: "1550 mm",
    chapter_4_spec3_label: "Dry weight",
    chapter_4_spec3_value: "~1250 kg",
    chapter_4_spec4_label: "Wet weight",
    chapter_4_spec4_value: "~1450 kg",
    chapter_5_title: "Product Video",
    chapter_5_tagline: "See it in action.",
    chapter_5_spec0_label: "Duration",
    chapter_5_spec0_value: "2:30 min",
    chapter_5_spec1_label: "Quality",
    chapter_5_spec1_value: "1080p HD",
    chapter_5_spec2_label: "Format",
    chapter_5_spec2_value: "MP4",
    // Hotspots for Guided Presentation
    hotspot_0_title: "Silent Diesel Generator",
    hotspot_0_desc: "62.5 kVA silent diesel generator overview. Engineered for premium reliability and quiet operation.",
    hotspot_0_spec0_label: "Rating",
    hotspot_0_spec0_value: "62.5 kVA",
    hotspot_0_spec1_label: "Phase",
    hotspot_0_spec1_value: "3 Phase",
    hotspot_0_spec2_label: "Compliance",
    hotspot_0_spec2_value: "CPCB IV+",
    hotspot_1_title: "Turbocharged Engine",
    hotspot_1_desc: "Turbocharged 4-cylinder diesel engine. Built for continuous duty and tight load response.",
    hotspot_1_spec0_label: "Configuration",
    hotspot_1_spec0_value: "4-cylinder, inline",
    hotspot_1_spec1_label: "Aspiration",
    hotspot_1_spec1_value: "Turbocharged",
    hotspot_1_spec2_label: "Displacement",
    hotspot_1_spec2_value: "~3.9 L",
    hotspot_1_spec3_label: "Cooling",
    hotspot_1_spec3_value: "Water-cooled",
    hotspot_1_spec4_label: "Fuel",
    hotspot_1_spec4_value: "High-speed diesel",
    hotspot_2_title: "Power Output",
    hotspot_2_desc: "Industrial brushless alternator with copper windings. Clean, stable 3-phase power for sensitive loads.",
    hotspot_2_spec0_label: "Rating",
    hotspot_2_spec0_value: "62.5 kVA / 50 kW",
    hotspot_2_spec1_label: "Voltage",
    hotspot_2_spec1_value: "415 V",
    hotspot_2_spec2_label: "Frequency",
    hotspot_2_spec2_value: "50 Hz",
    hotspot_2_spec3_label: "Phase",
    hotspot_2_spec3_value: "3-phase, 4-wire",
    hotspot_2_spec4_label: "Power factor",
    hotspot_2_spec4_value: "0.8 lagging",
    hotspot_3_title: "Sound & Enclosure",
    hotspot_3_desc: "Acoustic enclosure with louvered ventilation. CPCB IV+ compliant. Engineered to disappear into its environment.",
    hotspot_3_spec0_label: "Sound level",
    hotspot_3_spec0_value: "75 dB(A) @ 1m",
    hotspot_3_spec1_label: "At 7m",
    hotspot_3_spec1_value: "63 dB(A)",
    hotspot_3_spec2_label: "Construction",
    hotspot_3_spec2_value: "1.6 mm CRCA panels",
    hotspot_3_spec3_label: "Insulation",
    hotspot_3_spec3_value: "PU foam, 50 mm",
    hotspot_3_spec4_label: "Finish",
    hotspot_3_spec4_value: "7-tank powder coat",
    hotspot_4_title: "Dimensions & Weight",
    hotspot_4_desc: "Side profile view of silent diesel generator. Compact footprint, easy to site and service.",
    hotspot_4_spec0_label: "Length",
    hotspot_4_spec0_value: "2400 mm",
    hotspot_4_spec1_label: "Width",
    hotspot_4_spec1_value: "1050 mm",
    hotspot_4_spec2_label: "Height",
    hotspot_4_spec2_value: "1550 mm",
    hotspot_4_spec3_label: "Dry weight",
    hotspot_4_spec3_value: "~1250 kg",
    hotspot_4_spec4_label: "Wet weight",
    hotspot_4_spec4_value: "~1450 kg",
  },
  ekl15ShowcaseData: {
    productName: "EKL 15 kVA (2 Cyl) DG Set",
    pageLabel: "Showcase",
    pageSubtitle: "6-chapter walkthrough of the Escorts-powered 15 kVA silent generator.",
    presentModeBtn: "Present Mode",
    chapter_0_title: "EKL 15 kVA Silent DG Set",
    chapter_0_tagline: "Compact power, CPCB IV compliant — built for demanding environments.",
    chapter_0_h0_label: "Prime power",
    chapter_0_h0_value: "15",
    chapter_0_h0_suffix: " kVA",
    chapter_0_h1_label: "Sound @ 1m",
    chapter_0_h1_value: "70",
    chapter_0_h1_suffix: " dB(A)",
    chapter_0_h2_label: "Heritage",
    chapter_0_h2_value: "27",
    chapter_0_h2_suffix: "+ yrs",
    chapter_0_spec0_label: "Model",
    chapter_0_spec0_value: "EKL15-IV (2 Cyl)",
    chapter_0_spec1_label: "Rating",
    chapter_0_spec1_value: "15 kVA / 12 kWe",
    chapter_0_spec2_label: "Compliance",
    chapter_0_spec2_value: "CPCB IV",
    chapter_1_title: "Engine",
    chapter_1_tagline: "Escorts G15-IV — 2-cylinder, naturally aspirated, built for reliability.",
    chapter_1_spec0_label: "Make",
    chapter_1_spec0_value: "Escorts",
    chapter_1_spec1_label: "Model",
    chapter_1_spec1_value: "G15-IV",
    chapter_1_spec2_label: "Configuration",
    chapter_1_spec2_value: "2-cylinder inline",
    chapter_1_spec3_label: "Aspiration",
    chapter_1_spec3_value: "Natural aspiration",
    chapter_1_spec4_label: "Displacement",
    chapter_1_spec4_value: "1.56 L",
    chapter_1_spec5_label: "Bore × Stroke",
    chapter_1_spec5_value: "95 × 110 mm",
    chapter_1_spec6_label: "Cooling",
    chapter_1_spec6_value: "Air cooled",
    chapter_1_spec7_label: "Speed",
    chapter_1_spec7_value: "1500 RPM",
    chapter_1_spec8_label: "Gross Power (PRP)",
    chapter_1_spec8_value: "14.1 kWm / 19 hp",
    chapter_2_title: "Power Output",
    chapter_2_tagline: "Stable 3-phase power at 415 V / 50 Hz for sensitive loads.",
    chapter_2_spec0_label: "Make",
    chapter_2_spec0_value: "Stamford",
    chapter_2_spec1_label: "Frame",
    chapter_2_spec1_value: "S0L1-P1",
    chapter_2_spec2_label: "Rating",
    chapter_2_spec2_value: "15 kVA / 12 kWe",
    chapter_2_spec3_label: "Voltage",
    chapter_2_spec3_value: "415 V (L-L)",
    chapter_2_spec4_label: "Current",
    chapter_2_spec4_value: "20.88 A",
    chapter_2_spec5_label: "Frequency",
    chapter_2_spec5_value: "50 Hz",
    chapter_2_spec6_label: "Power Factor",
    chapter_2_spec6_value: "0.8 lagging",
    chapter_2_spec7_label: "Insulation",
    chapter_2_spec7_value: "H Class",
    chapter_2_spec8_label: "Efficiency @ 75%",
    chapter_2_spec8_value: "86.4%",
    chapter_2_spec9_label: "Efficiency @ 100%",
    chapter_2_spec9_value: "83.5%",
    chapter_3_title: "Sound & Enclosure",
    chapter_3_tagline: "CPCB IV compliant. Designed for residential and commercial sites.",
    chapter_3_spec0_label: "Sound level",
    chapter_3_spec0_value: "70 dB(A) @ 1m",
    chapter_3_spec1_label: "Compliance",
    chapter_3_spec1_value: "CPCB IV",
    chapter_3_spec2_label: "Protection",
    chapter_3_spec2_value: "IP23",
    chapter_3_spec3_label: "Design Ambient",
    chapter_3_spec3_value: "40°C",
    chapter_3_spec4_label: "Altitude",
    chapter_3_spec4_value: "Up to 1000 m",
    chapter_3_spec5_label: "Cooling airflow",
    chapter_3_spec5_value: "0.58 m³/sec",
    chapter_4_title: "Control Panel",
    chapter_4_tagline: "DEIF SGC 120 — Advanced microprocessor controller with AMF & CANbus.",
    chapter_4_spec0_label: "Controller",
    chapter_4_spec0_value: "DEIF SGC 120",
    chapter_4_spec1_label: "Display",
    chapter_4_spec1_value: "LCD backlit, full graphics",
    chapter_4_spec2_label: "Operation",
    chapter_4_spec2_value: "Auto / Manual / Remote",
    chapter_4_spec3_label: "AMF",
    chapter_4_spec3_value: "Supported",
    chapter_4_spec4_label: "Comms",
    chapter_4_spec4_value: "USB / RS-485 / CANbus",
    chapter_4_spec5_label: "Protection",
    chapter_4_spec5_value: "IP65 with gasket",
    chapter_4_spec6_label: "Operating Temp",
    chapter_4_spec6_value: "-20 to 65°C",
    chapter_4_spec7_label: "Event Log",
    chapter_4_spec7_value: "100 events",
    chapter_5_title: "Dimensions & Weight",
    chapter_5_tagline: "Compact footprint — easy to site, transport and service.",
    chapter_5_spec0_label: "Length",
    chapter_5_spec0_value: "1760 mm",
    chapter_5_spec1_label: "Width",
    chapter_5_spec1_value: "950 mm",
    chapter_5_spec2_label: "Height",
    chapter_5_spec2_value: "1495 mm",
    chapter_5_spec3_label: "Dry weight",
    chapter_5_spec3_value: "~70 kg (open set)",
    chapter_5_spec4_label: "Day fuel tank",
    chapter_5_spec4_value: "Included",
    chapter_5_spec5_label: "Lube oil",
    chapter_5_spec5_value: "15W40 CI4, 5.5 L",
    hotspot_0_title: "EKL 15 kVA DG Set",
    hotspot_0_desc: "Escorts-powered 15 kVA silent generator. Compact, CPCB IV compliant — built for demanding environments.",
    hotspot_0_spec0_label: "Rating",
    hotspot_0_spec0_value: "15 kVA",
    hotspot_0_spec1_label: "Phase",
    hotspot_0_spec1_value: "3 Phase",
    hotspot_0_spec2_label: "Compliance",
    hotspot_0_spec2_value: "CPCB IV",
    hotspot_1_title: "Escorts G15-IV Engine",
    hotspot_1_desc: "2-cylinder, naturally aspirated diesel engine with electronic governor for stable frequency output.",
    hotspot_1_spec0_label: "Cylinders",
    hotspot_1_spec0_value: "2 inline",
    hotspot_1_spec1_label: "Displacement",
    hotspot_1_spec1_value: "1.56 L",
    hotspot_1_spec2_label: "Speed",
    hotspot_1_spec2_value: "1500 RPM",
    hotspot_2_title: "Stamford Alternator",
    hotspot_2_desc: "Brushless, self-excited single-bearing alternator with double layer concentric winding.",
    hotspot_2_spec0_label: "Rating",
    hotspot_2_spec0_value: "15 kVA / 12 kWe",
    hotspot_2_spec1_label: "Voltage",
    hotspot_2_spec1_value: "415 V",
    hotspot_2_spec2_label: "Power Factor",
    hotspot_2_spec2_value: "0.8 lagging",
    hotspot_3_title: "Sound & Enclosure",
    hotspot_3_desc: "CPCB IV compliant acoustic enclosure for silent residential and commercial operation.",
    hotspot_3_spec0_label: "Sound level",
    hotspot_3_spec0_value: "70 dB(A) @ 1m",
    hotspot_3_spec1_label: "Compliance",
    hotspot_3_spec1_value: "CPCB IV",
    hotspot_3_spec2_label: "Protection",
    hotspot_3_spec2_value: "IP23",
    hotspot_4_title: "Dimensions & Weight",
    hotspot_4_desc: "Compact open-set dimensions — easy to transport, site and service.",
    hotspot_4_spec0_label: "Length",
    hotspot_4_spec0_value: "1760 mm",
    hotspot_4_spec1_label: "Width",
    hotspot_4_spec1_value: "950 mm",
    hotspot_4_spec2_label: "Height",
    hotspot_4_spec2_value: "1495 mm",
    hotspot_4_spec3_label: "Dry weight",
    hotspot_4_spec3_value: "~70 kg",
  },
};

export type CMSSection = keyof typeof defaultContent;

// A helper to get content, preferring LocalStorage (for the mock CMS) then Sanity (if configured)
export async function fetchContent(type: CMSSection) {
  // Try to get from local storage first (for our in-app CMS)
  const localData = localStorage.getItem(`cms_${type}`);
  if (localData) {
    try {
      return JSON.parse(localData);
    } catch (e) {
      console.error("Error parsing local CMS data", e);
    }
  }

  // If we had a real Sanity project ID, we would fetch here
  if (import.meta.env.VITE_SANITY_PROJECT_ID) {
    try {
      const query = `*[_type == "${type}"][0]`;
      const data = await sanityClient.fetch(query);
      if (data) return data;
    } catch (error) {
      console.error(`Failed to fetch ${type} from Sanity:`, error);
    }
  }

  // Fallback to defaults
  return defaultContent[type];
}

export async function saveContent(type: CMSSection, data: any) {
  // In a real Sanity setup, this would be a mutation via API (requires token)
  // For now, we save to local storage so the presentation tool works standalone
  localStorage.setItem(`cms_${type}`, JSON.stringify(data));
  return true;
}
